repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run ty check
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: website-lint
        name: website lint
        entry: npm --prefix assets/website run lint
        language: system
        pass_filenames: false
        files: ^assets/website/
